config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root to: "meals#index"

  resources :meals
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/meal.rb
# == Schema Information
#
# Table name: meals
#
#  id          :bigint           not null, primary key
#  description :string
#  link        :string
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Meal < ApplicationRecord

  validates_presence_of :name, :description
  validates :name, uniqueness: true
  validates :description, length: { minimum: 25, message: "Please provide a longer description!" }

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @meals = Meal.all
  end

  def new
    @meal = Meal.new
  end

  def create
    @meal = Meal.new(meal_params)
    if @meal.save
      redirect_to meals_path, notice: "Meal successfully created!"
    else
      render :new
    end
  end

  def edit
    @meal = Meal.find(params[:id])
  end

  def update
    # TODO: this will only be possible by Meal creator or group admin
    @meal = Meal.find(params[:id])
    if @meal.update(meal_params)
      redirect_to meal_path(@meal), notice: "Meal successfully updated!"
    else
      render :edit
    end
  end

  def show
    @meal = Meal.find(params[:id])
  end

  def destroy
    @meal = Meal.find(params[:id])
    @meal.destroy
    # look: status: :see_other is a Rails 7 feature (https://guides.rubyonrails.org/getting_started.html#deleting-an-article)
    redirect_to meals_url, status: :see_other, alert: "Meal successfully deleted!"
  end

  private

  def meal_params
    params.require(:meal).
      permit(:name, :description, :link)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <%= content_tag(:div, message, class: "flash #{type}") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DinnerSpinner</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render "layouts/flash" %>

      <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#"><%= link_to image_tag("dinners", size: "50x50"), root_path %></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Dinner Spinner</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
    <%# </header> %>

    <%= yield %>
  </body>
</html>

app/views/meals/_form.html.erb
<%= bootstrap_form_with(model: @meal, local: true) do |m| %>
  <%= m.text_field :name, required: true %>
  <%= m.text_area :description, rows: 5, required: true %>
  <%= m.text_area :link %>
  <%= m.submit %>
<% end %>

app/views/meals/edit.html.erb
<h1>Editing Meal: <%= @meal.name %></h1>

<%# look: form submission didn't work with addition of form partial %>
<%# without the turbo_frame_tag. need to read up on this %>
<%# https://github.com/hotwired/turbo-rails/issues/12 %>

<%= turbo_frame_tag "meal" do %>
  <%= render 'form', meal: @meal %>
<% end %>

app/views/meals/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <% @meals.each do |m| %>
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
                <p class="card-text" style="text-align: center;"><%= link_to m.name.capitalize, m %></p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group w-100">
                    <%= link_to "View", m, class: "btn btn-outline-secondary" %>
                    <%= link_to "Edit", edit_meal_path(m), class: "btn btn-outline-secondary" %>
                  </div>
                </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<section class="admin">
  <%= link_to "Add New Meal", new_meal_path, class:"button" %>
</section>

app/views/meals/new.html.erb
<h1>Create a New Meal</h1>

<%= turbo_frame_tag "meal" do %>
  <%= render 'form', meal: @meal %>
<% end %>

app/views/meals/show.html.erb
<section class="meal-details">
  <div class="details">
    <h1><%= @meal.name %></h1>
    <p>
      <%= @meal.description %>
    </p>

    <p>
      <%= @meal.link %>
    </p>
  </div>
</section>

<section class="admin">
  <%= link_to "Edit Meal", edit_meal_path, class:"button" %>
  <%# look: now turbo_method: :delete (Rails 7)  %>
  <%= link_to "Delete Meal", @meal,  class: "button", data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
</section>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <section class="errors">
    <h2>
      Oops! Your meal could not be saved.
    </h2>
    <h3>
      Please correct the following
      <%= pluralize(object.errors.size, "error") %>:
    </h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>